name: iismee
version: 1.0.0+1
publish_to: none
description: IISMEE Developed By MI Vokasi UNESA
environment: 
  sdk: '>=2.18.2 <3.7.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.4.0
  rolling_switch: 0.0.2
  circular_profile_avatar: 2.0.5
  percent_indicator: ^4.2.3
  drawerbehavior: 2.2.2
  flutter_svg: ^2.0.4
  provider: ^6.0.5
  data_table_2: ^2.4.1
  google_fonts: ^4.0.3
  flutter_dropzone: ^3.0.5
  calendar_view: ^1.0.0
  intl: ^0.17.0
  timelines: 0.1.0
  flutter_chat_ui: 1.6.6
  file_picker: ^5.2.2
  uuid: ^3.0.7
  mime: ^1.0.2
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  open_file: ^2.1.1
  open_filex: ^4.3.1
  ionicons: 0.2.2
  fl_chart: ^0.61.0
  dropdown_button2: ^2.0.0
  google_sign_in: 6.0.2
  fluttertoast: 8.2.1
  firebase_core: ^2.9.0
  firebase: 9.0.3
  firebase_auth: ^4.4.0
  flutter: 
    sdk: flutter
  http: ^0.13.5
  http_parser: ^4.0.2
  extended_image: ^7.0.2
  flutter_pdfview: ^1.3.0
  webview_flutter: ^4.0.7
  pdfx: ^2.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
  uses-material-design: true

